/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef HEYZAP_AUTODEFS_H
#define HEYZAP_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_HEYZAP_NAME "Heyzap"
#define S3E_EXT_HEYZAP_HASH 0x1df9ed6

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("Heyzap", 10)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !HEYZAP_AUTODEFS_H */
