/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*HeyzapRegister_t)(HeyzapCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*HeyzapUnRegister_t)(HeyzapCallback cbid, s3eCallback fn);
typedef       void(*HeyzapStart_t)(const char* pubId);
typedef       void(*HeyzapFetchInterstitial_t)(const char* tag);
typedef       void(*HeyzapShowInterstitial_t)(const char* tag);
typedef       void(*HeyzapFetchVideo_t)(const char* tag);
typedef       void(*HeyzapShowVideo_t)(const char* tag);
typedef       void(*HeyzapFetchRewarded_t)(const char* tag);
typedef       void(*HeyzapShowRewarded_t)(const char* tag);
typedef       void(*HeyzapStartTestActivity_t)();

/**
 * struct that gets filled in by HeyzapRegister
 */
typedef struct HeyzapFuncs
{
    HeyzapRegister_t m_HeyzapRegister;
    HeyzapUnRegister_t m_HeyzapUnRegister;
    HeyzapStart_t m_HeyzapStart;
    HeyzapFetchInterstitial_t m_HeyzapFetchInterstitial;
    HeyzapShowInterstitial_t m_HeyzapShowInterstitial;
    HeyzapFetchVideo_t m_HeyzapFetchVideo;
    HeyzapShowVideo_t m_HeyzapShowVideo;
    HeyzapFetchRewarded_t m_HeyzapFetchRewarded;
    HeyzapShowRewarded_t m_HeyzapShowRewarded;
    HeyzapStartTestActivity_t m_HeyzapStartTestActivity;
} HeyzapFuncs;
