/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "Heyzap_autodefs.h"
#include "s3eEdk.h"
#include "Heyzap.h"
//Declarations of Init and Term functions
extern s3eResult HeyzapInit();
extern void HeyzapTerminate();


s3eResult HeyzapRegister(HeyzapCallback cbid, s3eCallback fn, void* pData)
{
    return s3eEdkCallbacksRegister(S3E_EXT_HEYZAP_HASH, HEYZAP_CALLBACK_MAX, cbid, fn, pData, 0);
};

s3eResult HeyzapUnRegister(HeyzapCallback cbid, s3eCallback fn)
{
    return s3eEdkCallbacksUnRegister(S3E_EXT_HEYZAP_HASH, HEYZAP_CALLBACK_MAX, cbid, fn);
}

void HeyzapRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[13];
    funcPtrs[0] = (void*)HeyzapRegister;
    funcPtrs[1] = (void*)HeyzapUnRegister;
    funcPtrs[2] = (void*)HeyzapStart;
    funcPtrs[3] = (void*)HeyzapFetchInterstitial;
    funcPtrs[4] = (void*)HeyzapShowInterstitial;
    funcPtrs[5] = (void*)HeyzapFetchVideo;
    funcPtrs[6] = (void*)HeyzapShowVideo;
    funcPtrs[7] = (void*)HeyzapFetchRewarded;
    funcPtrs[8] = (void*)HeyzapShowRewarded;
    funcPtrs[9] = (void*)HeyzapShowBanner;
    funcPtrs[10] = (void*)HeyzapHideBanner;
    funcPtrs[11] = (void*)HeyzapDestroyBanner;
    funcPtrs[12] = (void*)HeyzapStartTestActivity;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[13] = { 0 };

    /*
     * Register the extension
     */
s3eEdkRegister("Heyzap", funcPtrs, sizeof(funcPtrs), flags, HeyzapInit, HeyzapTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int HeyzapStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&HeyzapRegisterExt;
    return 0;
}

int g_HeyzapVal = HeyzapStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    HeyzapRegisterExt();
}
#endif

#endif
