/*
 * (C) 2001-2012 Marmalade. All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Marmalade.
 *
 * This file consists of source code released by Marmalade under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_HEYZAP_H
#define S3E_EXT_HEYZAP_H

enum HeyzapCallback{
	SHOW, CLICK, HIDE, FAILED_TO_SHOW, AVAILABLE, FAILED_TO_FETCH, AUDIO_STARTED, AUDIO_FINISHED,INCENTIVE_COMPLETE, INCENTIVE_INCOMPLETE
};

#define HEYZAP_CALLBACK_MAX 10000
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the Heyzap extension is available.
 */
s3eBool HeyzapAvailable();

/**
 * Registers a callback to be called for an operating system event.
 *
 * The available callback types are listed in @ref HeyzapCallback.
 * @param cbid ID of the event for which to register.
 * @param fn callback function.
 * @param userdata Value to pass to the @e userdata parameter of @e NotifyFunc.
 * @return
 *  - @ref S3E_RESULT_SUCCESS if no error occurred.
 *  - @ref S3E_RESULT_ERROR if the operation failed.\n
 *
 * @see HeyzapUnRegister
 * @note For more information on the system data passed as a parameter to the callback
 * registered using this function, see the @ref HeyzapCallback enum.
 */
s3eResult HeyzapRegister(HeyzapCallback cbid, s3eCallback fn, void* userData);

/**
 * Unregister a callback for a given event.
 * @param cbid ID of the callback to unregister.
 * @param fn Callback Function.
 * @return
 * - @ref S3E_RESULT_SUCCESS if no error occurred.
 * - @ref S3E_RESULT_ERROR if the operation failed.\n
 * @note For more information on the systemData passed as a parameter to the callback
 * registered using this function, see the HeyzapCallback enum.
 * @note It is not necessary to define a return value for any registered callback.
 * @see HeyzapRegister
 */
s3eResult HeyzapUnRegister(HeyzapCallback cbid, s3eCallback fn);

void HeyzapStart(const char* pubId);

void HeyzapFetchInterstitial(const char* tag);

void HeyzapShowInterstitial(const char* tag);

void HeyzapFetchVideo(const char* tag);

void HeyzapShowVideo(const char* tag);

void HeyzapFetchRewarded(const char* tag);

void HeyzapShowRewarded(const char* tag);

void HeyzapStartTestActivity();

// \cond HIDDEN_DEFINES
S3E_END_C_DECL
// \endcond

#endif /* !S3E_EXT_HEYZAP_H */
